api:
  image:
    repository: quay.io/gamebench/node-backend
    pullSecrets: []
  livenessProbe:
    httpGet:
      path: /v1/health
      port: 5000
    initialDelaySeconds: 60
    periodSeconds: 30
  readinessProbe:
    httpGet:
      path: /v1/info/version
      port: 5000
    initialDelaySeconds: 60
    periodSeconds: 30
  replicas: 1
  resources: {}
  #  requests:
  #    memory: 1Gi
  #    cpu: 1
  #  limits:
  #    memory: 1Gi
  service:
    type: ClusterIP

apiTokenSecret: ""
application:
  authJwtSecret:
  host:
  port: "443"
  urlScheme: "https"
  httpProxy:
  httpsProxy:
  noProxy:
encryptionKey: ""
fileStorage:
  cacheType: "disk"
  gcsBucket: ""
  gcsPathPrefix: ""
  gcsProjectId: ""
  type: "disk"
googleApplicationCredentials: ""
image:
  tag: v2.8.0
ingress:
  enabled: false
  hosts: []
license:
  contents: ""
  signature: ""
logLevel:
persistence:
  enabled: true
  existingClaim: ""
  size: "10Gi"
  storageClassName: ""
postgres:
  database: gamebench
  host: ""
  password: ""
  port: "5432"
  username: ""
redis:
  auth: ""
  host: ""
  port: "6379"
setupPassword: ""
smtp:
  from: ""
  host: ""
  user: ""
  pass: ""
  port: ""
  tls: "false"
  secure: "false"
  name: ""
ui:
  image:
    repository: quay.io/gamebench/ang4-frontend
    pullSecrets: []
  replicas: 1
  resources: {}
  #  requests:
  #    memory: 512Mi
  #    cpu: 250m
  #  limits:
  #    memory: 512Mi
  service:
    type: ClusterIP

worker:
  replicas: 1
  resources: {}
  #  requests:
  #    memory: 1Gi
  #    cpu: 1
  #  limits:
  #    memory: 1Gi
