apiVersion: v1
data:
  ALLOW_FREE_USER_SIGNUP: "false"
  BACKEND_URL: {{ printf "%s://%s:%s" .Values.application.urlScheme .Values.application.host .Values.application.port }}
  {{ if .Values.application.dbLogLevel }}
  DB_LOG_LEVEL: "{{.Values.application.dbLogLevel}}"
  {{ end }}
  DEFAULT_SUBTYPE: company
  FILE_STORAGE_DISK_BASE_PATH: /var/gamebench/data/storage
  {{ if eq .Values.fileStorage.type "gcs" }}
  FILE_STORAGE_CACHE_TYPE: {{.Values.fileStorage.cacheType}}
  FILE_STORAGE_GCS_BUCKET: {{.Values.fileStorage.gcsBucket}}
  FILE_STORAGE_GCS_PATH_PREFIX: "{{.Values.fileStorage.gcsPathPrefix}}"
  FILE_STORAGE_GCS_PROJECT_ID: {{.Values.fileStorage.gcsProjectId}}
  {{ end }}
  FILE_STORAGE_TYPE: {{.Values.fileStorage.type }}
  FRONTEND_URL: {{ printf "%s://%s:%s" .Values.application.urlScheme .Values.application.host .Values.application.port }}
  GB_AUTH_JWT_SECRET: "{{.Values.application.authJwtSecret}}"
  GB_BASE_PATH: /var/gamebench/data
  GB_LICENSE_PATH: /var/gamebench/license
  {{ if .Values.googleApplicationCredentials }}
  GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/key.json
  {{ end }}
  {{ if .Values.application.logFormat }}
  LOG_FORMAT: "{{.Values.application.logFormat}}"
  {{ end }}
  {{ if .Values.logLevel }}
  LOG_LEVEL: "{{.Values.logLevel}}"
  {{ end }}
  MAIL_FROM: "{{ .Values.smtp.from }}"
  MAIL_HOST: "{{ .Values.smtp.host }}"
  MAIL_PORT: "{{.Values.smtp.port}}"
  MAIL_TLS: "{{.Values.smtp.tls}}"
  NODE_ENV: production
  POSTGRES_DATABASE: "{{.Values.postgres.database}}"
  POSTGRES_HOST: "{{.Values.postgres.host}}"
  POSTGRES_PORT: "{{.Values.postgres.port}}"
  REDIS_HOST: "{{.Values.redis.host}}"
  REDIS_PORT: "{{.Values.redis.port}}"
kind: ConfigMap
metadata:
  name: {{ template "gamebench.fullname" . }}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ template "gamebench.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
