apiVersion: v1
data:
  gamebench-license: {{ .Values.license.contents | quote }}
  gamebench-license.RSA-SHA256: {{ .Values.license.signature | quote }}
kind: Secret
metadata:
  name: {{ template "gamebench.fullname" . }}-license
  namespace: "{{.Release.Namespace}}"
  labels:
    app: {{ template "gamebench.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
