apiVersion: v1
data:
  API_TOKEN_SECRET: {{.Values.apiTokenSecret | b64enc | quote }}
  ENCRYPTION_KEY: {{.Values.encryptionKey | b64enc | quote }}
  ES_AUTH_PASS: {{.Values.elasticsearch.pass | b64enc | quote }}
  ES_AUTH_USER: {{.Values.elasticsearch.user | b64enc | quote }}
  MAIL_PASS: {{.Values.smtp.pass | b64enc | quote }}
  MAIL_USER: {{.Values.smtp.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{.Values.postgres.password | b64enc | quote }}
  POSTGRES_USERNAME: {{.Values.postgres.username | b64enc | quote }}
  REDIS_AUTH: {{.Values.redis.auth | b64enc | quote }}
  SETUP_JWT_SECRET: {{ randAlphaNum 30 | b64enc | quote }}
  SETUP_PASSWORD: {{ .Values.setupPassword | b64enc | quote }}
kind: Secret
metadata:
  name: {{ template "gamebench.fullname" . }}
  namespace: "{{.Release.Namespace}}"
  labels:
    app: {{ template "gamebench.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
